### PR TITLE
Created conda environment file.

### PR DESCRIPTION
**Pull request by RodolfoFerro**
Hey, I've just added the `environment.yml` file to create a conda environment (just as the `requirements.txt` file works).

Installation:
```bash
# Create conda environment as follows:
$ conda env create -f environment.yml
```

Activate/deactivate environment:
```bash
# Activate:
$ conda activate omdena

#Deactivate:
$ conda deactivate
```

### CODE REVIEW

**Comment by FavioVazquez** [comment]
@RodolfoFerro can you create an Issue about this and reference this PR there?

**Comment by FavioVazquez** [comment]
did you try this on MatrixDS @RodolfoFerro ?

**Comment by shpotes** [comment]
Works well for me (I use `source activate` instead of `conda activate`)

**Comment by RodolfoFerro** [comment]
I haven't tried it yet on MatrixDS @FavioVazquez. 🤔

**Pull request merged**
